### ISSUE TITLE
Wrong URL in your keysigning policy

### ISSUE THREAD

**Issue by fntlnz** [AlessandroMenti/AlessandroMenti.github.io#1]
I was going to verify your policy but the URL was wrong in https://github.com/AlessandroMenti/AlessandroMenti.github.io/blob/master/downloads/key-signing-policy-v1.0.txt#L10

The right one is: `https://www.alessandromenti.it/downloads/key-signing-policy-v1.0.txt`

**Comment by AlessandroMenti** [comment]
I have checked the URL in the [Markdown source file](https://github.com/AlessandroMenti/AlessandroMenti.github.io/blob/master/about.md), the relative URL is right (that's because the official URL for my Web site is https://www.alessandromenti.it: if you go to https://www.alessandromenti.it/about/ and scroll down to the "my certification policy" link, you can notice that the URL is correct).

**Comment by AlessandroMenti** [comment]
Sorry, I noticed that you were referring to the URl in the text file, I've reopened the issue.
